# Generated by Django 4.2.2 on 2023-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0004_remove_order_food_items_order_food_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmode',
            field=models.CharField(choices=[('CH', 'Cash'), ('CD', 'Card'), ('DW', 'Digital Wallet')], max_length=2, null=True),
        ),
    ]
